### ISSUE TITLE
使用preprocess生成数据后，运行微调脚本报错：module 'bmtrain.optim' has no attribute 'OptimManager'

### ISSUE THREAD

**Issue by yuye2133** [OpenBMB/CPM-Bee#11]
克隆了$ git clone -b main --single-branch https://github.com/OpenBMB/CPM-Bee.git
装了库：pip install -r requirements.txt
转换了数据
但是微调没跑通，报错如下：
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py:193 in <module>                              │
│                                                                                                  │
│   190 │   model: CPMBee,                                                                         │
│   191 │   optimizer: bmt.optim.AdamOffloadOptimizer,                                             │
│   192 │   lr_scheduler: bmt.lr_scheduler.WarmupLRScheduler,                                      │
│ ❱ 193 │   optim_manager: bmt.optim.OptimManager,                                                 │
│   194 ):                                                                                         │
│   195 │                                                                                          │
│   196 │   average_time = bmt.utils.AverageRecorder()                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'bmtrain.optim' has no attribute 'OptimManager'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py:193 in <module>                              │
│                                                                                                  │
│   190 │   model: CPMBee,                                                                         │
│   191 │   optimizer: bmt.optim.AdamOffloadOptimizer,                                             │
│   192 │   lr_scheduler: bmt.lr_scheduler.WarmupLRScheduler,                                      │
│ ❱ 193 │   optim_manager: bmt.optim.OptimManager,                                                 │
│   194 ):                                                                                         │
│   195 │                                                                                          │
│   196 │   average_time = bmt.utils.AverageRecorder()                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'bmtrain.optim' has no attribute 'OptimManager'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py:193 in <module>                              │
│                                                                                                  │
│   190 │   model: CPMBee,                                                                         │
│   191 │   optimizer: bmt.optim.AdamOffloadOptimizer,                                             │
│   192 │   lr_scheduler: bmt.lr_scheduler.WarmupLRScheduler,                                      │
│ ❱ 193 │   optim_manager: bmt.optim.OptimManager,                                                 │
│   194 ):                                                                                         │
│   195 │                                                                                          │
│   196 │   average_time = bmt.utils.AverageRecorder()                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'bmtrain.optim' has no attribute 'OptimManager'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py:193 in <module>                              │
│                                                                                                  │
│   190 │   model: CPMBee,                                                                         │
│   191 │   optimizer: bmt.optim.AdamOffloadOptimizer,                                             │
│   192 │   lr_scheduler: bmt.lr_scheduler.WarmupLRScheduler,                                      │
│ ❱ 193 │   optim_manager: bmt.optim.OptimManager,                                                 │
│   194 ):                                                                                         │
│   195 │                                                                                          │
│   196 │   average_time = bmt.utils.AverageRecorder()                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'bmtrain.optim' has no attribute 'OptimManager'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 94429) of binary: /opt/conda/bin/python3
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune_cpm_bee.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-28_22:57:29
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 94430)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-05-28_22:57:29
  host      : ubuntu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 94431)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-05-28_22:57:29
  host      : ubuntu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 94432)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-28_22:57:29
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 94429)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

直接运行推理没有报错
```
python text_generation.py
```
{'document': '中国最好的大学是<mask_0>', '<ans>': {'<mask_0>': '清华北大，世界最好的大学是麻省理工。'}}

**Comment by zh-zheng** [comment]
我们更新了一下`requirements.txt`，您升级一下BMTrain就可以了。
