### ISSUE TITLE
运行text_generation.py报错

### ISSUE THREAD

**Issue by qingfengcss** [OpenBMB/CPM-Bee#30]
Traceback (most recent call last):
  File "cpmbee_translator.py", line 2, in <module>
    from cpm_live.generation.bee import CPMBeeBeamSearch
  File "/home/css/CPM-Bee/src/cpm_live/generation/__init__.py", line 1, in <module>
    from .ant import CPMAntBeamSearch, CPMAntRandomSampling, CPMAntGeneration
  File "/home/css/CPM-Bee/src/cpm_live/generation/ant.py", line 4, in <module>
    from ..utils import pad
  File "/home/css/CPM-Bee/src/cpm_live/utils/__init__.py", line 1, in <module>
    from .config import Config
  File "/home/css/CPM-Bee/src/cpm_live/utils/config.py", line 20, in <module>
    from .log import logger
  File "/home/css/CPM-Bee/src/cpm_live/utils/log.py", line 27, in <module>
    logger = _get_logger()
  File "/home/css/CPM-Bee/src/cpm_live/utils/log.py", line 15, in _get_logger
    node_name = os.getenv("NODE_NAME", str(bmt.rank()))
  File "/opt/conda/lib/python3.8/site-packages/bmtrain-0.0.15-py3.8-linux-x86_64.egg/bmtrain/global_var.py", line 24, in rank
    return config['rank']
KeyError: 'rank'

运行demo直接报该错误，请问有什么方法解决吗，尝试在 text_generation.py中加入以下代码也不行
import os 
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '5678'

**Comment by xuguozhi** [comment]
同样遇到KeyError: 'rank'

**Comment by zh-zheng** [comment]
> Traceback (most recent call last): File "cpmbee_translator.py", line 2, in from cpm_live.generation.bee import CPMBeeBeamSearch File "/home/css/CPM-Bee/src/cpm_live/generation/**init**.py", line 1, in from .ant import CPMAntBeamSearch, CPMAntRandomSampling, CPMAntGeneration File "/home/css/CPM-Bee/src/cpm_live/generation/ant.py", line 4, in from ..utils import pad File "/home/css/CPM-Bee/src/cpm_live/utils/**init**.py", line 1, in from .config import Config File "/home/css/CPM-Bee/src/cpm_live/utils/config.py", line 20, in from .log import logger File "/home/css/CPM-Bee/src/cpm_live/utils/log.py", line 27, in logger = _get_logger() File "/home/css/CPM-Bee/src/cpm_live/utils/log.py", line 15, in _get_logger node_name = os.getenv("NODE_NAME", str(bmt.rank())) File "/opt/conda/lib/python3.8/site-packages/bmtrain-0.0.15-py3.8-linux-x86_64.egg/bmtrain/global_var.py", line 24, in rank return config['rank'] KeyError: 'rank'
> 
> 运行demo直接报该错误，请问有什么方法解决吗，尝试在 text_generation.py中加入以下代码也不行 import os os.environ['MASTER_ADDR'] = 'localhost' os.environ['MASTER_PORT'] = '5678'

看报错信息，您使用了0.0.15版本的BMTrain，本项目需要BMTrain的版本高于0.2.1
