### ISSUE TITLE
全参数微调时报错:TypeError: CheckpointBlock._named_members() got an unexpected keyword argument 'remove_duplicate'

### ISSUE THREAD

**Issue by yuye2133** [OpenBMB/CPM-Bee#46]
8卡机器，使用4，5，6，7这4块显卡；
默认安装的opendelta == 0.3.0
torch==2.0.0
transformers==4.28.1

全参数微调时报错如下：
TypeError: CheckpointBlock._named_members() got an unexpected keyword argument 'remove_duplicate'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8973) of binary: /opt/conda/bin/python

**Comment by zh-zheng** [comment]
BMTrain暂时不支持torch 2.0，正在适配中。请先按照`requirements.txt`安装依赖。

**Comment by yuye2133** [comment]
pip install torch==1.13.0 ，测试print(torch.cuda.device_count())，正常打印8
然后pip install -r requirements.txt；正常安装，运行微调时还是报错，日志如下
`
*****************************************
Traceback (most recent call last):
  File "/data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py", line 19, in <module>
    import bmtrain as bmt
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/__init__.py", line 16, in <module>
    from . import optim
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/__init__.py", line 1, in <module>
    from .adam import AdamOptimizer
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/adam.py", line 4, in <module>
    from . import _cuda as C
ImportError: /opt/conda/lib/python3.10/site-packages/bmtrain/optim/_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
Traceback (most recent call last):
  File "/data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py", line 19, in <module>
    import bmtrain as bmt
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/__init__.py", line 16, in <module>
    from . import optim
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/__init__.py", line 1, in <module>
    from .adam import AdamOptimizer
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/adam.py", line 4, in <module>
    from . import _cuda as C
ImportError: /opt/conda/lib/python3.10/site-packages/bmtrain/optim/_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
Traceback (most recent call last):
  File "/data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py", line 19, in <module>
    import bmtrain as bmt
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/__init__.py", line 16, in <module>
    from . import optim
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/__init__.py", line 1, in <module>
    from .adam import AdamOptimizer
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/adam.py", line 4, in <module>
    from . import _cuda as C
ImportError: /opt/conda/lib/python3.10/site-packages/bmtrain/optim/_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
Traceback (most recent call last):
  File "/data/rain-llm/code/CPM-Bee/src/finetune_cpm_bee.py", line 19, in <module>
    import bmtrain as bmt
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/__init__.py", line 16, in <module>
    from . import optim
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/__init__.py", line 1, in <module>
    from .adam import AdamOptimizer
  File "/opt/conda/lib/python3.10/site-packages/bmtrain/optim/adam.py", line 4, in <module>
    from . import _cuda as C
ImportError: /opt/conda/lib/python3.10/site-packages/bmtrain/optim/_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9920) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune_cpm_bee.py FAILED
`

**Comment by jeffchy** [comment]
same error

**Comment by Danny-wenya** [comment]
请问这个报错决解了吗？这个看起来和torch版本或torch和gpu的兼容性
有关，我在我的程序中更换了torch版本后出现了这个报错。
