### ISSUE TITLE
多轮对话微调，数据问题

### ISSUE THREAD

**Issue by spf1983** [OpenBMB/CPM-Bee#98]
使用10b模型，做多轮对话全参数微调训练，训练数据完全按照说明文档里的构建的，如下：
```
{"input":"<问题>技术问题 \n<答案>","<ans>":"您好"}
{"input":"<问题>技术问题 \n<答案>您好 \n<问题>关于文档同步，假如我在极空间的文件修改了，然后在电脑端对原相同文件也进行了另外的修改，那此时启动手动同步的话，它会以哪个文件为准进行同步呢 \n<答案>","<ans>":"您稍等哈"}
```

但是开始训练的时候，报错了：ValueError: Invalid token <问题>

```
Traceback (most recent call last):
  File "/data/codes/CPM-Bee/src/scripts/../finetune_cpm_bee.py", line 432, in <module>
    main()
  File "/data/codes/CPM-Bee/src/scripts/../finetune_cpm_bee.py", line 428, in main
    finetune(args, tokenizer, model, optimizer, lr_scheduler, optim_manager)
  File "/data/codes/CPM-Bee/src/scripts/../finetune_cpm_bee.py", line 229, in finetune
    for iteration, data in enumerate(dataloader):
  File "/data/codes/CPM-Bee/src/cpm_live/training_tasks/bee/finetune.py", line 57, in __iter__
    for batch in self.__batch_iter():
  File "/data/codes/CPM-Bee/src/cpm_live/training_tasks/bee/finetune.py", line 42, in __batch_iter
    batch = self._packer.add_data(self._ds_cfg)
  File "/data/codes/CPM-Bee/src/cpm_live/training_tasks/bee/pretrain.py", line 636, in add_data
    ) = self.build_instance(config)
  File "/data/codes/CPM-Bee/src/cpm_live/training_tasks/bee/pretrain.py", line 448, in build_instance
    ) = self.data_to_id(inp)
  File "/data/codes/CPM-Bee/src/cpm_live/training_tasks/bee/pretrain.py", line 364, in data_to_id
    return convert_data_to_id(
  File "/data/codes/CPM-Bee/src/cpm_live/training_tasks/bee/pretrain.py", line 212, in convert_data_to_id
    raise ValueError("Invalid token {}".format(token))
ValueError: Invalid token <问题>
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 517260) of binary: /home/yanfa/miniconda3/envs/CPM-Bee/bin/python
Traceback (most recent call last):
  File "/home/yanfa/miniconda3/envs/CPM-Bee/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/yanfa/miniconda3/envs/CPM-Bee/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/yanfa/miniconda3/envs/CPM-Bee/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/yanfa/miniconda3/envs/CPM-Bee/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/yanfa/miniconda3/envs/CPM-Bee/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yanfa/miniconda3/envs/CPM-Bee/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../finetune_cpm_bee.py FAILED
```

各位大佬，这个问题该怎么解决？

**Comment by spf1983** [comment]
使用官方提供的另一种多轮对话格式，解决了训练数据的问题，
成功训练的格式如下：
`{"input": "用户： 你好，我想问一下明天天气会怎样？\n<sep>AI： 你好！明天的天气会根据你所在的城市而异，请告诉我你所在的城市。\n<sep>用户： 我在北京。\n<sep>AI：", "<ans>": " 明天北京天气预计为阴转多云，最高气温26℃，最低气温18℃。"}`
报错的格式如下：
`{"input": "<问题>你好，我想问一下明天天气会怎样？\n<答案>你好！明天的天气会根据你所在的城市而异，请告诉我你所在的城市。\n<问题>我在北京。\n<答案>", "<ans>": " 明天北京天气预计为阴转多云，最高气温26℃，最低气温18℃。"}`
